export const ADD_BLOG_LOADING = "ADD_BLOG_LOADING";
export const ADD_BLOG_SUCESS = "ADD_BLOG_SUCESS";
export const ADD_BLOG_FAIL = "ADD_BLOG_FAIL";

export const UPDATE_BLOG_LOADING = "UPDATE_BLOG_LOADING";
export const UPDATE_BLOG_SUCESS = "UPDATE_BLOG_SUCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";

export const GET_BLOG_LOADING = "GET_BLOG_LOADING";
export const GET_BLOG_SUCESS = "GET_BLOG_SUCESS";
export const GET_BLOG_FAIL = "GET_BLOG_FAIL";

export const ADD_CATEGORIES_LOADING = "ADD_CATEGORIES_LOADING";
export const ADD_CATEGORIES_SUCESS = "ADD_CATEGORIES_SUCESS";
export const ADD_CATEGORIES_FAIL = "ADD_CATEGORIES_FAIL";

export const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING";
export const GET_CATEGORIES_SUCESS = "GET_CATEGORIES_SUCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const UPDATE_CATEGORIES_LOADING = "UPDATE_CATEGORIES_LOADING";
export const UPDATE_CATEGORIES_SUCESS = "UPDATE_CATEGORIES_SUCESS";
export const UPDATE_CATEGORIES_FAIL = "UPDATE_CATEGORIES_FAIL";
