export const ADD_BLOG_LOADING = "ADD_BLOG_LOADING";
export const ADD_BLOG_SUCESS = "ADD_BLOG_SUCESS";
export const ADD_BLOG_FAIL = "ADD_BLOG_FAIL";

export const UPDATE_BLOG_LOADING = "UPDATE_BLOG_LOADING";
export const UPDATE_BLOG_SUCESS = "UPDATE_BLOG_SUCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";

export const GET_BLOG_LOADING = "GET_BLOG_LOADING";
export const GET_BLOG_SUCESS = "GET_BLOG_SUCESS";
export const GET_BLOG_FAIL = "GET_BLOG_FAIL";

export const DETAILS_BLOG_LOADING = "DETAILS_BLOG_LOADING";
export const DETAILS_BLOG_SUCESS = "DETAILS_BLOG_SUCESS";
export const DETAILS_BLOG_FAIL = "DETAILS_BLOG_FAIL";

export const DELETE_BLOG_LOADING = "DELETE_BLOG_LOADING";
export const DELETE_BLOG_SUCESS = "DELETE_BLOG_SUCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";

export const RESET_BLOG = "RESET_BLOG";

export const ADD_CATEGORIES_LOADING = "ADD_CATEGORIES_LOADING";
export const ADD_CATEGORIES_SUCESS = "ADD_CATEGORIES_SUCESS";
export const ADD_CATEGORIES_FAIL = "ADD_CATEGORIES_FAIL";

export const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING";
export const GET_CATEGORIES_SUCESS = "GET_CATEGORIES_SUCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const UPDATE_CATEGORIES_LOADING = "UPDATE_CATEGORIES_LOADING";
export const UPDATE_CATEGORIES_SUCESS = "UPDATE_CATEGORIES_SUCESS";
export const UPDATE_CATEGORIES_FAIL = "UPDATE_CATEGORIES_FAIL";

export const DELETE_CATEGORIES_LOADING = "DELETE_CATEGORIES_LOADING";
export const DELETE_CATEGORIES_SUCESS = "DELETE_CATEGORIES_SUCESS";
export const DELETE_CATEGORIES_FAIL = "DELETE_CATEGORIES_FAIL";

export const RESET_CATEGORIES = "RESET_CATEGORIES";
