export const JOB_LIST_LOADING = "JOB_LIST_LOADING";
export const JOB_LIST_SUCCESS = "JOB_LIST_SUCCESS";
export const JOB_LIST_FAIL = "JOB_LIST_FAIL";

export const JOB_DETAILS_LOADING = "JOB_DETAILS_LOADING";
export const JOB_DETAILS_SUCCESS = "JOB_DETAILS_SUCCESS";
export const JOB_DETAILS_FAIL = "JOB_DETAILS_FAIL";

export const JOB_ADD_LOADING = "JOB_ADD_LOADING";
export const JOB_ADD_SUCCESS = "JOB_ADD_SUCCESS";
export const JOB_ADD_FAIL = "JOB_ADD_FAIL";
export const JOB_ADD_RESET = "JOB_ADD_RESET";

export const UPDATE_JOB_LOADING = "UPDATE_JOB_LOADING";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_FAIL = "UPDATE_JOB_FAIL";
export const UPDATE_JOB_RESET = "UPDATE_JOB_RESET";

export const APPLY_JOB_LOADING = "APPLY_JOB_LOADING";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAIL = "APPLY_JOB_FAIL";
export const APPLY_JOB_RESET = "APPLY_JOB_RESET";
