export const NEWS_SUBMIT_LOADING = "NEWS_SUBMIT_LOADING";
export const NEWS_SUBMIT_SUCCESS = "NEWS_SUBMIT_SUCCESS";
export const NEWS_SUBMIT_FAIL = "NEWS_SUBMIT_FAIL";

export const CONTACT_US_LOADING = "CONTACT_US_LOADING";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";
