export const NEWS_SUBMIT_LOADING = "NEWS_SUBMIT_LOADING";
export const NEWS_SUBMIT_SUCCESS = "NEWS_SUBMIT_SUCCESS";
export const NEWS_SUBMIT_FAIL = "NEWS_SUBMIT_FAIL";

export const CONTACT_US_LOADING = "CONTACT_US_LOADING";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";

export const CONTACT_LIST_LOADING = "CONTACT_LIST_LOADING";
export const CONTACT_LIST_SUCCESS = "CONTACT_LIST_SUCCESS";
export const CONTACT_LIST_FAIL = "CONTACT_LIST_FAIL";

export const NEWS_LIST_LOADING = "NEWS_LIST_LOADING";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL";
