export const ADD_ITEMS_LOADING = "ADD_ITEMS_LOADING";
export const ADD_ITEMS_SUCCESS = "ADD_ITEMS_SUCCESS";
export const ADD_ITEMS_FAIL = "ADD_ITEMS_FAIL";
export const ADD_ITEMS_RESET = "ADD_ITEMS_RESET";

export const ADD_PRIVACY_LOADING = "ADD_PRIVACY_LOADING";
export const ADD_PRIVACY_SUCCESS = "ADD_PRIVACY_SUCCESS";
export const ADD_PRIVACY_FAIL = "ADD_PRIVACY_FAIL";
export const ADD_PRIVACY_RESET = "ADD_PRIVACY_RESET";

export const GET_TERMS_LOADING = "GET_TERMS_LOADING";
export const GET_TERMS_SUCCESS = "GET_TERMS_SUCCESS";
export const GET_TERMS_FAIL = "GET_TERMS_FAIL";

export const GET_PRIVACY_LOADING = "GET_PRIVACY_LOADING";
export const GET_PRIVACY_SUCCESS = "GET_PRIVACY_SUCCESS";
export const GET_PRIVACY_FAIL = "GET_PRIVACY_FAIL";
